=== Silverpeas/Silverpeas-Core/core-configuration/src/main/config/xmlcomponents/component.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (C) 2000 - 2016 Silverpeas

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    As a special exception to the terms and conditions of version 3.0 of
    the GPL, you may redistribute this Program in connection with Free/Libre
    Open Source Software ("FLOSS") applications as described in Silverpeas's
    FLOSS exception.  You should have received a copy of the text describing
    the FLOSS exception, and it is also available here:
    "http://www.silverpeas.org/docs/core/legal/floss_exception.html"

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

-->

<xs:schema xmlns="http://silverpeas.org/xml/ns/component" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://silverpeas.org/xml/ns/component">
  <xs:element name="WAComponent" type="WAComponentType">
    <xs:annotation>
      <xs:documentation>Copyright (C) 2000 - 2013 Silverpeas

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    As a special exception to the terms and conditions of version 3.0 of
    the GPL, you may redistribute this Program in connection with Free/Libre
    Open Source Software ("FLOSS") applications as described in Silverpeas's
    FLOSS exception.  You should have recieved a copy of the text describing
    the FLOSS exception, and it is also available here:
    "http://www.silverpeas.org/docs/core/legal/floss_exception.html"

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see &lt;http://www.gnu.org/licenses/>.
      </xs:documentation>
    </xs:annotation>
  </xs:element>

  <xs:simpleType name="behavior" final="restriction" >
    <xs:restriction base="xs:string">
      <xs:enumeration value="topicTracker" />
      <xs:enumeration value="workflow" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="ProfileType" >
    <xs:complexContent>
      <xs:extension base="ProfileDescription" >
        <xs:attribute type="xs:string" name="name"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="multilang">
    <xs:sequence>
      <xs:element type="MessageType" name="message" maxOccurs="unbounded" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ProfileDescription">
    <xs:sequence>
      <xs:element name="label" type="multilang" />
      <xs:element name="help" type="multilang" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="MessageType">
    <xs:simpleContent>
      <xs:extension base="xs:string" >
        <xs:attribute type="xs:string" name="lang"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="ParameterType">
    <xs:sequence>
      <xs:element name="name" type="xs:string" />
      <xs:element name="label" type="multilang" />
      <xs:element name="order" type="xs:int" />
      <xs:element name="mandatory" type="xs:boolean" />
      <xs:element name="value" type="xs:string"/>
      <xs:element name="options" maxOccurs="unbounded" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element type="ParameterOptionType" name="option" maxOccurs="unbounded" minOccurs="0"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="type">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="checkbox"/>
            <xs:enumeration value="select"/>
            <xs:enumeration value="xmltemplates"/>
            <xs:enumeration value="text"/>
            <xs:enumeration value="radio"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="size" type="xs:int" minOccurs="0" />
      <xs:element name="updatable">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="always"/>
            <xs:enumeration value="creation"/>
            <xs:enumeration value="never" />
            <xs:enumeration value="hidden" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="multilang" name="help"/>
      <xs:element type="multilang" name="warning" minOccurs="0" maxOccurs="1" />
      <xs:element type="xs:string" name="personalSpaceValue" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ParameterOptionType">
    <xs:sequence>
      <xs:element name="name" type="multilang"/>
      <xs:element name="value" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="GroupOfParametersType">
    <xs:sequence>
      <xs:element name="label" type="multilang" />
      <xs:element name="description" type="multilang"/>
      <xs:element name="help" type="multilang" minOccurs="0"/>
      <xs:element name="order" type="xs:int" />
      <xs:element name="parameters" minOccurs="1" maxOccurs="1">
        <xs:complexType>
          <xs:sequence>
            <xs:element type="ParameterType" name="parameter" maxOccurs="unbounded" minOccurs="1"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="name" type="xs:token"/>
  </xs:complexType>

  <xs:complexType name="WAComponentType">
    <xs:sequence>
      <xs:element type="xs:string" name="name"/>
      <xs:element name="behaviors" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element type="behavior" name="behavior" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element type="multilang" name="label"/>
      <xs:element type="multilang" name="description"/>
      <xs:element type="multilang" name="suite"/>
      <xs:element type="xs:boolean" name="visible"/>
      <xs:element type="xs:boolean" name="visibleInPersonalSpace" minOccurs="0" maxOccurs="1" />
      <xs:element type="xs:boolean" name="portlet"/>
      <xs:element name="router" type="xs:string" minOccurs="0" />
      <xs:element name="profiles">
        <xs:complexType>
          <xs:sequence>
            <xs:element type="ProfileType" name="profile" maxOccurs="unbounded" minOccurs="0"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="groupsOfParameters" minOccurs="0" maxOccurs="1">
        <xs:complexType>
          <xs:sequence>
            <xs:element type="GroupOfParametersType" name="groupOfParameters" maxOccurs="unbounded" minOccurs="1"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="parameters" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element type="ParameterType" name="parameter" maxOccurs="unbounded" minOccurs="0"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== Silverpeas/Silverpeas-Core/lib-core/src/test/resources/xmlcomponents/almanach.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (C) 2000 - 2013 Silverpeas

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    As a special exception to the terms and conditions of version 3.0 of
    the GPL, you may redistribute this Program in connection with Free/Libre
    Open Source Software ("FLOSS") applications as described in Silverpeas's
    FLOSS exception.  You should have received a copy of the text describing
    the FLOSS exception, and it is also available here:
    "http://www.silverpeas.org/docs/core/legal/floss_exception.html"

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

-->

<WAComponent xmlns="http://silverpeas.org/xml/ns/component" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://silverpeas.org/xml/ns/component http://www.silverpeas.org/xsd/component.xsd">
  <name>almanach</name>
  <label>
    <message lang="fr">Almanach</message>
    <message lang="en">Almanach</message>
  </label>
  <description>
    <message lang="fr">Permet de créer et de visualiser les différents agendas d'événements définis dans les
      espaces et sous-espaces collaboratifs. A chaque événement peuvent être associés des fichiers
      joints. La visualisation s'effectue sur plusieurs échelles de temps.
    </message>
    <message lang="en">Enable to create and aggregate agendas from collaborative spaces or subspaces. Events can
      have attachments. You can viw events using different time scales.
    </message>
  </description>
  <suite>
    <message lang="fr">02 Gestion Collaborative</message>
    <message lang="en">02 Collaborative Management</message>
  </suite>
  <visible>true</visible>
  <portlet>true</portlet>
  <profiles>
    <profile name="admin">
      <label>
        <message lang="fr">Gestionnaire</message>
        <message lang="en">Administrator</message>
      </label>
      <help>
        <message lang="fr">Gestionnaire</message>
        <message lang="en">Administrator</message>
      </help>
    </profile>
    <profile name="publisher">
      <label>
        <message lang="fr">Publieur</message>
        <message lang="en">Publisher</message>
      </label>
      <help>
        <message lang="fr">Publieur</message>
        <message lang="en">Publisher</message>
      </help>
    </profile>
    <profile name="user">
      <label>
        <message lang="fr">Lecteur</message>
        <message lang="en">Reader</message>
      </label>
      <help>
        <message lang="fr">Lecteur</message>
        <message lang="en">Reader</message>
      </help>
    </profile>
  </profiles>
  <parameters>
    <parameter>
      <name>usePdc</name>
      <label>
        <message lang="fr">Classification PDC</message>
        <message lang="en">Classification Scheme</message>
      </label>
      <order>1</order>
      <mandatory>true</mandatory>
      <value>no</value>
      <type>checkbox</type>
      <updatable>always</updatable>
      <help>
        <message lang="fr">Les événements saisis au sein de cette instance pourront être classés sur le Plan de
          Classement
        </message>
        <message lang="en">The events will be classified on the classification scheme.</message>
      </help>
    </parameter>
    <parameter>
      <name>useAgregation</name>
      <label>
        <message lang="fr">Agrégation d'Almanachs</message>
        <message lang="en">Almanach Aggregation</message>
      </label>
      <order>2</order>
      <mandatory>true</mandatory>
      <value>no</value>
      <type>checkbox</type>
      <updatable>always</updatable>
      <help>
        <message lang="fr">Cet Almanach pourra contenir des évènements d'Almanachs appartenant à des sous-espaces
          de l'espace de cet Almanach.
        </message>
        <message lang="en">This almanach can aggregate events from other almanachs in subspaces of the space
          containing this almanach.
        </message>
      </help>
    </parameter>
    <parameter>
      <name>weekendNotVisible</name>
      <label>
        <message lang="fr">Masquer les week-ends</message>
        <message lang="en">Hide week-ends</message>
      </label>
      <order>3</order>
      <mandatory>true</mandatory>
      <value>no</value>
      <type>checkbox</type>
      <updatable>always</updatable>
      <help>
        <message lang="fr">Permet d'alléger l'interface et d'optimiser l'affichage du reste de la semaine</message>
        <message lang="en">Hide week-ends, thus lightening the GUI.</message>
      </help>
    </parameter>
    <parameter>
      <name>rss</name>
      <label>
        <message lang="fr">Flux RSS</message>
        <message lang="en">RSS</message>
      </label>
      <order>4</order>
      <mandatory>false</mandatory>
      <value>N</value>
      <type>checkbox</type>
      <updatable>always</updatable>
      <help>
        <message lang="fr">Permet de générer un flux RSS des événements de cet Almanach.</message>
        <message lang="en">Produce a RSS stream for the events of this almanach.</message>
      </help>
    </parameter>
    <parameter>
      <name>directAccess</name>
      <label>
        <message lang="fr">Accès transversal</message>
        <message lang="en">Aggregation type</message>
      </label>
      <order>5</order>
      <mandatory>false</mandatory>
      <value>0</value>
      <options>
        <option>
          <name>
            <message lang="fr">Tous</message>
            <message lang="en">All</message>
          </name>
          <value>0</value>
        </option>
        <option>
          <name>
            <message lang="fr">Ceux de l'espace</message>
            <message lang="en">Those from the same space</message>
          </name>
          <value>1</value>
        </option>
        <option>
          <name>
            <message lang="fr">Ceux de l'espace et sous espaces</message>
            <message lang="en">Those from the same space and its subspaces.</message>
          </name>
          <value>2</value>
        </option>
        <option>
          <name>
            <message lang="fr">Aucun</message>
            <message lang="en">None</message>
          </name>
          <value>3</value>
        </option>
      </options>
      <type>select</type>
      <updatable>always</updatable>
      <help>
        <message lang="fr">Permet de choisir quelles autres instances du composant Almanach sont accessibles depuis
          la liste déroulante.
        </message>
        <message lang="en">Choose which almanachs can be aggregated into this almanach.</message>
      </help>
    </parameter>
  </parameters>
</WAComponent>
