=== Silverpeas/Silverpeas-Core/lib-core/src/test/resources/com/silverpeas/wysiwyg/dynamicvalue/pool/ConnectionSettings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (C) 2000 - 2012 Silverpeas

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    As a special exception to the terms and conditions of version 3.0 of
    the GPL, you may redistribute this Program in connection with Free/Libre
    Open Source Software ("FLOSS") applications as described in Silverpeas's
    FLOSS exception.  You should have received a copy of the text describing
    the FLOSS exception, and it is also available here:
    "http://www.silverpeas.org/legal/licensing"

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="ConnectionInformation">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="connectionType" type="xs:string" minOccurs="1" />
				<xs:element name="JndiName" type="xs:string" minOccurs="0" />
				<xs:element name="driver" type="xs:string" minOccurs="0" />
				<xs:element name="url" type="xs:string" minOccurs="0" />
				<xs:element name="user" type="xs:string" minOccurs="0" />
				<xs:element name="password" type="xs:string" minOccurs="0" />
				<xs:element name="numTestsPerEvictionRun" type="xs:int" minOccurs="0" />
				<xs:element name="maxActive" type="xs:int" minOccurs="0" />
				<xs:element name="maxIdle" type="xs:int" minOccurs="0" />
				<xs:element name="maxWait" type="xs:long" minOccurs="0" />
				<xs:element name="timeBetweenEvictionRunsMillis" type="xs:long" minOccurs="0" />
				<xs:element name="minEvictableIdleTimeMillis" type="xs:long" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Silverpeas/Silverpeas-Core/config-core/src/main/config/properties/com/silverpeas/wysiwyg/dynamicvalue/pool/ConnectionSettings.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (C) 2000 - 2012 Silverpeas

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    As a special exception to the terms and conditions of version 3.0 of
    the GPL, you may redistribute this Program in connection with Free/Libre
    Open Source Software ("FLOSS") applications as described in Silverpeas's
    FLOSS exception.  You should have received a copy of the text describing
    the FLOSS exception, and it is also available here:
    "http://www.silverpeas.org/legal/licensing"

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

-->

<ConnectionInformation  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ConnectionSettings.xsd">
	<!--
		three possible choices for the connection type : JNDI,JDBC
		JNDI : use existing JNDI resource to access database
		JDBC : use  JDBC url to access database
	-->
	<connectionType>JNDI</connectionType>
	<JndiName>java:/datasources/silverpeas-jdbc</JndiName>
	<!-- complete following information only if you use JDBC to access database -->
	<driver>org.postgresql.Driver</driver>
	<url>jdbc:postgresql://localhost:5432/SilverpeasV5</url>
	<user>postgres</user>
	<password>postgres</password>
	<!--connection pool parameters-->
	   <!-- the number of objects to examine during each run of the idle object evictor thread (if any). -->
	    <numTestsPerEvictionRun>-1</numTestsPerEvictionRun>
		<!-- The maximum number of active connections that can be allocated from this pool at the same time, or non-positive for no limit.-->
		<maxActive>10</maxActive>
		<!--The maximum number of active connections that can remain idle in the pool, without extra ones being released, or negative for no limit.-->
		<maxIdle>10 </maxIdle>
		<!-- The maximum number of milliseconds that the pool will wait (when there are no available connections) for a connection to be returned before throwing an exception, or -1 to wait indefinitely.-->
		<maxWait>1000</maxWait>
		<!--The number of milliseconds to sleep between runs of the idle-object evictor thread. -->
		<!--When negative, no idle-object evictor thread will run. Use this parameter only when you want the evictor thread to run.-->
		<timeBetweenEvictionRunsMillis>-1</timeBetweenEvictionRunsMillis>
		<!--The minimum amount of time an object, if active, may sit idle in the pool before it is eligible -->
		<!--for eviction by the idle-object evictor. If a negative value is supplied, no objects are evicted due to idle time alone.-->
		<minEvictableIdleTimeMillis>30000</minEvictableIdleTimeMillis>
</ConnectionInformation>
