=== Silverpeas/Silverpeas-Core/config-core/src/main/config/web/weblib.war/exchange/v408/SilverpeasExchange.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--

    Copyright (C) 2000 - 2012 Silverpeas

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    As a special exception to the terms and conditions of version 3.0 of
    the GPL, you may redistribute this Program in connection with Free/Libre
    Open Source Software ("FLOSS") applications as described in Silverpeas's
    FLOSS exception.  You should have received a copy of the text describing
    the FLOSS exception, and it is also available here:
    "http://www.silverpeas.org/legal/licensing"

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

-->

<!-- edited with XMLSpy v2005 sp1 U (http://www.xmlspy.com) by Nicolas EYSSERIC (Silverpeas) -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:sp="http://intranoo.oevo.com/websilverpeas/exchange/v408" targetNamespace="http://intranoo.oevo.com/websilverpeas/exchange/v408" elementFormDefault="qualified" attributeFormDefault="unqualified" version="0.1">
	<xsd:element name="SilverpeasExchange">
		<xsd:annotation>
			<xsd:documentation>content of a Silverpeas exchange document</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="publications" minOccurs="0">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="publication" type="sp:PublicationType" maxOccurs="unbounded"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="repositories" minOccurs="0">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="repository" type="sp:RepositoryType" minOccurs="0" maxOccurs="unbounded"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="pdc" type="sp:PlanDeClassementType" minOccurs="0">
					<xsd:annotation>
						<xsd:documentation>le Plan de Classement est associé aux publications dans le fichier d'échange</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element name="topicTrees" minOccurs="0">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="topicTree" type="sp:TopicTreeType" maxOccurs="unbounded"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="components" minOccurs="0">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="component" type="sp:ComponentType" maxOccurs="unbounded"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute name="targetComponentId" type="xsd:string" use="optional"/>
			<xsd:attribute name="usePOI" type="xsd:boolean" use="optional"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="DBModelType">
		<xsd:sequence>
			<xsd:element name="dbModelText" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="dbModelImagePath" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:int" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="WysiwygType">
		<xsd:attribute name="path" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="XMLModelType">
		<xsd:sequence>
			<xsd:element name="xmlField" type="sp:XMLField" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="XMLField">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="value" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="PublicationContentType">
		<xsd:annotation>
			<xsd:documentation>content can be stored in wysiwyg mode or DB model</xsd:documentation>
		</xsd:annotation>
		<xsd:choice>
			<xsd:element name="wysiwyg" type="sp:WysiwygType"/>
			<xsd:element name="dbModel" type="sp:DBModelType"/>
			<xsd:element name="xmlModel" type="sp:XMLModelType"/>
		</xsd:choice>
	</xsd:complexType>
	<xsd:complexType name="PublicationType">
		<xsd:sequence>
			<xsd:element name="publicationHeader" type="sp:PublicationHeaderType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>le Header de la publication est optionnel. Si homis alors les règles de gestion font l'importation par défaut</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="publicationContent" type="sp:PublicationContentType" minOccurs="0"/>
			<xsd:element name="attachments" minOccurs="0">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="attachment" type="sp:AttachmentType" maxOccurs="unbounded"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="topicPositions">
				<xsd:annotation>
					<xsd:documentation>chaque publication est contenu dans au moins un topic</xsd:documentation>
				</xsd:annotation>
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="topicPosition" type="sp:TopicPositionType" maxOccurs="unbounded"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="pdcPositions" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>le PDC est optionnel</xsd:documentation>
				</xsd:annotation>
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="pdcPosition" type="sp:PdcPositionType" maxOccurs="unbounded"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:int" use="optional"/>
		<xsd:attribute name="componentId" type="xsd:string" use="optional"/>
	</xsd:complexType>
	<xsd:complexType name="PlanDeClassementType">
		<xsd:sequence>
			<xsd:element name="axis" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:complexContent>
						<xsd:extension base="sp:AxisType"/>
					</xsd:complexContent>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="PublicationHeaderType">
		<xsd:sequence>
			<xsd:element name="name">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="400"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="description">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="2000"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="creationDate" type="xsd:date" minOccurs="0"/>
			<xsd:element name="beginDate" type="xsd:date" minOccurs="0"/>
			<xsd:element name="endDate" type="xsd:date" minOccurs="0"/>
			<xsd:element name="creatorId" type="xsd:int" minOccurs="0"/>
			<xsd:element name="creatorName" type="xsd:string" minOccurs="0"/>
			<xsd:element name="importance" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:int">
						<xsd:enumeration value="1"/>
						<xsd:enumeration value="2"/>
						<xsd:enumeration value="3"/>
						<xsd:enumeration value="4"/>
						<xsd:enumeration value="5"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="version" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="100"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="keywords" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="1000"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="status" type="sp:PublicationStatus" default="Valid" minOccurs="0"/>
			<xsd:element name="vignette" type="xsd:string" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="AttachmentType">
		<xsd:sequence>
			<xsd:element name="name" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="100"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="description" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="1000"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:int" use="optional"/>
		<xsd:attribute name="path" type="xsd:string" use="required"/>
		<xsd:attribute name="updateRule" type="xsd:string" use="optional"/>
	</xsd:complexType>
	<xsd:complexType name="TopicPositionType">
		<xsd:attribute name="topicId" type="xsd:int" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="TopicTreeType">
		<xsd:sequence>
			<xsd:element name="topic" type="sp:TopicType"/>
		</xsd:sequence>
		<xsd:attribute name="componentId" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="TopicType">
		<xsd:sequence>
			<xsd:element name="name">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="1000"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="description">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="2000"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="topic" type="sp:TopicType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:int" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="PdcPositionType">
		<xsd:sequence>
			<xsd:element name="axisPosition" type="sp:AxisPositionType" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="AxisPositionType">
		<xsd:attribute name="axisId" type="xsd:int" use="required"/>
		<xsd:attribute name="pdcValuePath" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="AxisType">
		<xsd:complexContent>
			<xsd:extension base="sp:PdcValueType">
				<xsd:attribute name="id" type="xsd:int" use="optional"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:complexType name="PdcValueType">
		<xsd:sequence>
			<xsd:element name="name">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="255"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="description" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="1000"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="pdcValue" type="sp:PdcValueType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="pdcValuePath" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="RepositoryType">
		<xsd:attribute name="path" type="xsd:string" use="required"/>
		<xsd:attribute name="componentId" type="xsd:string" use="required"/>
		<xsd:attribute name="topicId" type="xsd:int" use="required"/>
		<xsd:attribute name="massiveType" type="sp:MassiveImportType" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="ComponentType">
		<xsd:annotation>
			<xsd:documentation>une instance de composant</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="name">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="100"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="description" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="400"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:simpleType name="MassiveImportType">
		<xsd:annotation>
			<xsd:documentation>type possible pour l'importation massive (0 : non récursif, 1 : récursif sans réplication de l�__arborescence de répertoire ou 2 : récursif avec réplication)</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="NO_RECURSIVE"/>
			<xsd:enumeration value="RECURSIVE_NOREPLICATE"/>
			<xsd:enumeration value="RECURSIVE_REPLICATE"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="PublicationStatus">
		<xsd:annotation>
			<xsd:documentation>valide, visible etc.</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Draft"/>
			<xsd:enumeration value="ToValidate"/>
			<xsd:enumeration value="Valid"/>
			<xsd:enumeration value="UnValidate"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="KmeliaComponent">
		<xsd:annotation>
			<xsd:documentation>kmelia147 pour Theme Tracker</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="kmelia241"/>
			<xsd:enumeration value="kmelia147"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== Silverpeas/Silverpeas-Core/web-core/src/test/resources/com/silverpeas/importExport/lot5.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--

    Copyright (C) 2000 - 2013 Silverpeas

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    As a special exception to the terms and conditions of version 3.0 of
    the GPL, you may redistribute this Program in connection with Free/Libre
    Open Source Software ("FLOSS") applications as described in Silverpeas's
    FLOSS exception.  You should have received a copy of the text describing
    the FLOSS exception, and it is also available here:
    "http://www.silverpeas.org/docs/core/legal/floss_exception.html"

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

-->

<SilverpeasExchange xmlns="http://intranoo.oevo.com/websilverpeas/exchange/v5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://intranoo.oevo.com/websilverpeas/exchange/v5 file:///opt/Silverpeas/SilverpeasExchange.xsd">
	<topicTrees>
		<topicTree componentId="kmelia16">
			<topic id="678">
				<name>1-Informations aux INTERNES</name>
				<description>Informations aux INTERNES</description>
				<topic id="679">
					<name>2-Test</name>
					<description>Test</description>
				</topic>
				<topic id="680">
					<name>3-Test</name>
					<description>Test</description>
				</topic>
			</topic>
		</topicTree>
		<topicTree componentId="kmelia16">
			<topic id="681">
				<name>2-Informations aux EXTERNES</name>
				<description>Informations aux EXTERNES</description>
				<topic id="681">
					<name>AAA</name>
					<description></description>
				</topic>
				<topic id="682">
					<name>BBB</name>
					<description></description>
				</topic>
			</topic>
		</topicTree>
	</topicTrees>	
</SilverpeasExchange>

=== Silverpeas/Silverpeas-Core/core-web/src/test-awaiting/resources/com/silverpeas/importExport/lot2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (C) 2000 - 2013 Silverpeas

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    As a special exception to the terms and conditions of version 3.0 of
    the GPL, you may redistribute this Program in connection with Free/Libre
    Open Source Software ("FLOSS") applications as described in Silverpeas's
    FLOSS exception.  You should have received a copy of the text describing
    the FLOSS exception, and it is also available here:
    "http://www.silverpeas.org/docs/core/legal/floss_exception.html"

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

-->

<SilverpeasExchange targetComponentId="kmelia621" xmlns="http://intranoo.oevo.com/websilverpeas/exchange/v308" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://intranoo.oevo.com/websilverpeas/exchange/v5 http://intranoo.oevo.com/websilverpeas/exchange/v5/SilverpeasExchange.xsd">
	<publications>
		<publication>
			<publicationHeader>
				<name>Publication importï¿½e</name>
				<description>la description de la publication xml</description>
				<creationDate>2005-01-01</creationDate>
				<beginDate>2005-01-02</beginDate>
				<endDate>2006-01-03</endDate>
				<creatorId>98</creatorId>
				<importance>1</importance>
				<version>1.0</version>
				<keywords>publication castor xml</keywords>
				<status>Valid</status>
				<vignette>\\Silver-fs\documents\tests\lot2\logo_silverpeas.gif</vignette>
			</publicationHeader>
			<attachments>
				<attachment path="\\Silver-fs\documents\tests\lot2\dossier1\sousdossier\Tryptique.doc"/>
				<attachment path="\\Silver-fs\documents\tests\lot2\dossier2\MANUEL BDD.xls"/>
				<attachment path="\\Silver-fs\documents\tests\lot2\dossier2\logo_silverpeas.gif"/>
			</attachments>
			<topicPositions>
				<topicPosition topicId="289"/>
				<topicPosition topicId="290"/>
			</topicPositions>
			<pdcPositions>
				<pdcPosition>
					<axisPosition axisId="3" pdcValuePath="/0/2/9/"/>
					<axisPosition axisId="4" pdcValuePath="/0/1/"/>
				</pdcPosition>
				<pdcPosition>
					<axisPosition axisId="3" pdcValuePath="/0/1/4/6/"/>
					<axisPosition axisId="4" pdcValuePath="/0/3/"/>
				</pdcPosition>
			</pdcPositions>
		</publication>
	</publications>
</SilverpeasExchange>

=== Silverpeas/Silverpeas-Core/web-core/src/test/resources/com/silverpeas/importExport/lot1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (C) 2000 - 2012 Silverpeas

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    As a special exception to the terms and conditions of version 3.0 of
    the GPL, you may redistribute this Program in connection with Free/Libre
    Open Source Software ("FLOSS") applications as described in Silverpeas's
    FLOSS exception.  You should have received a copy of the text describing
    the FLOSS exception, and it is also available here:
    "http://www.silverpeas.org/docs/core/legal/floss_exception.html"

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

-->

<SilverpeasExchange targetComponentId="kmelia621" xmlns="http://intranoo.oevo.com/websilverpeas/exchange/v308" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://intranoo.oevo.com/websilverpeas/exchange/v5 http://intranoo.oevo.com/websilverpeas/exchange/v5/SilverpeasExchange.xsd">
	<publications>
		<publication>
			<attachments>
				<attachment path="\\Silver-fs\documents\tests\lot1\dossier1\sousdossier\Tryptique.doc"/>
				<attachment path="\\Silver-fs\documents\tests\lot1\dossier2\MANUEL BDD.xls"/>
				<attachment path="\\Silver-fs\documents\tests\lot1\dossier2\logo_silverpeas.gif"/>
			</attachments>
			<topicPositions>
				<topicPosition topicId="289"/>
				<topicPosition topicId="290"/>
			</topicPositions>
		</publication>
	</publications>
</SilverpeasExchange>
